package utilHibernate;
// Generated 16/03/2019 12:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer idciudad;
     private String ciuNombre;
     private Date ciuFechaRegistro;
     private Set concesionarios = new HashSet(0);

    public Ciudad() {
    }

    public Ciudad(String ciuNombre, Date ciuFechaRegistro, Set concesionarios) {
       this.ciuNombre = ciuNombre;
       this.ciuFechaRegistro = ciuFechaRegistro;
       this.concesionarios = concesionarios;
    }
   
    public Integer getIdciudad() {
        return this.idciudad;
    }
    
    public void setIdciudad(Integer idciudad) {
        this.idciudad = idciudad;
    }
    public String getCiuNombre() {
        return this.ciuNombre;
    }
    
    public void setCiuNombre(String ciuNombre) {
        this.ciuNombre = ciuNombre;
    }
    public Date getCiuFechaRegistro() {
        return this.ciuFechaRegistro;
    }
    
    public void setCiuFechaRegistro(Date ciuFechaRegistro) {
        this.ciuFechaRegistro = ciuFechaRegistro;
    }
    public Set getConcesionarios() {
        return this.concesionarios;
    }
    
    public void setConcesionarios(Set concesionarios) {
        this.concesionarios = concesionarios;
    }




}


