package utilHibernate;
// Generated 16/03/2019 12:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int cliIdentificacion;
     private String cliNombres;
     private String cliApellidos;
     private String cliDireccion;
     private String cliCiudad;
     private String cliTelefono;
     private String cliCelular;
     private Integer cliTipo;
     private Date cliFechaNac;
     private String cliCorreo;
     private String cliDescripcion;
     private Date cliFechaRegistro;
     private Set pqrses = new HashSet(0);
     private Set ventas = new HashSet(0);
     private Set garantias = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int cliIdentificacion) {
        this.cliIdentificacion = cliIdentificacion;
    }
    public Cliente(int cliIdentificacion, String cliNombres, String cliApellidos, String cliDireccion, String cliCiudad, String cliTelefono, String cliCelular, Integer cliTipo, Date cliFechaNac, String cliCorreo, String cliDescripcion, Date cliFechaRegistro, Set pqrses, Set ventas, Set garantias) {
       this.cliIdentificacion = cliIdentificacion;
       this.cliNombres = cliNombres;
       this.cliApellidos = cliApellidos;
       this.cliDireccion = cliDireccion;
       this.cliCiudad = cliCiudad;
       this.cliTelefono = cliTelefono;
       this.cliCelular = cliCelular;
       this.cliTipo = cliTipo;
       this.cliFechaNac = cliFechaNac;
       this.cliCorreo = cliCorreo;
       this.cliDescripcion = cliDescripcion;
       this.cliFechaRegistro = cliFechaRegistro;
       this.pqrses = pqrses;
       this.ventas = ventas;
       this.garantias = garantias;
    }
   
    public int getCliIdentificacion() {
        return this.cliIdentificacion;
    }
    
    public void setCliIdentificacion(int cliIdentificacion) {
        this.cliIdentificacion = cliIdentificacion;
    }
    public String getCliNombres() {
        return this.cliNombres;
    }
    
    public void setCliNombres(String cliNombres) {
        this.cliNombres = cliNombres;
    }
    public String getCliApellidos() {
        return this.cliApellidos;
    }
    
    public void setCliApellidos(String cliApellidos) {
        this.cliApellidos = cliApellidos;
    }
    public String getCliDireccion() {
        return this.cliDireccion;
    }
    
    public void setCliDireccion(String cliDireccion) {
        this.cliDireccion = cliDireccion;
    }
    public String getCliCiudad() {
        return this.cliCiudad;
    }
    
    public void setCliCiudad(String cliCiudad) {
        this.cliCiudad = cliCiudad;
    }
    public String getCliTelefono() {
        return this.cliTelefono;
    }
    
    public void setCliTelefono(String cliTelefono) {
        this.cliTelefono = cliTelefono;
    }
    public String getCliCelular() {
        return this.cliCelular;
    }
    
    public void setCliCelular(String cliCelular) {
        this.cliCelular = cliCelular;
    }
    public Integer getCliTipo() {
        return this.cliTipo;
    }
    
    public void setCliTipo(Integer cliTipo) {
        this.cliTipo = cliTipo;
    }
    public Date getCliFechaNac() {
        return this.cliFechaNac;
    }
    
    public void setCliFechaNac(Date cliFechaNac) {
        this.cliFechaNac = cliFechaNac;
    }
    public String getCliCorreo() {
        return this.cliCorreo;
    }
    
    public void setCliCorreo(String cliCorreo) {
        this.cliCorreo = cliCorreo;
    }
    public String getCliDescripcion() {
        return this.cliDescripcion;
    }
    
    public void setCliDescripcion(String cliDescripcion) {
        this.cliDescripcion = cliDescripcion;
    }
    public Date getCliFechaRegistro() {
        return this.cliFechaRegistro;
    }
    
    public void setCliFechaRegistro(Date cliFechaRegistro) {
        this.cliFechaRegistro = cliFechaRegistro;
    }
    public Set getPqrses() {
        return this.pqrses;
    }
    
    public void setPqrses(Set pqrses) {
        this.pqrses = pqrses;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getGarantias() {
        return this.garantias;
    }
    
    public void setGarantias(Set garantias) {
        this.garantias = garantias;
    }




}


