package utilHibernate;
// Generated 16/03/2019 12:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Concesionario generated by hbm2java
 */
public class Concesionario  implements java.io.Serializable {


     private Integer idconcesionario;
     private Ciudad ciudad;
     private String conNombre;
     private String conDireccion;
     private String conTelefonoFijo;
     private String conCelular;
     private Date conFechaRegistro;
     private Set tallers = new HashSet(0);

    public Concesionario() {
    }

	
    public Concesionario(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public Concesionario(Ciudad ciudad, String conNombre, String conDireccion, String conTelefonoFijo, String conCelular, Date conFechaRegistro, Set tallers) {
       this.ciudad = ciudad;
       this.conNombre = conNombre;
       this.conDireccion = conDireccion;
       this.conTelefonoFijo = conTelefonoFijo;
       this.conCelular = conCelular;
       this.conFechaRegistro = conFechaRegistro;
       this.tallers = tallers;
    }
   
    public Integer getIdconcesionario() {
        return this.idconcesionario;
    }
    
    public void setIdconcesionario(Integer idconcesionario) {
        this.idconcesionario = idconcesionario;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public String getConNombre() {
        return this.conNombre;
    }
    
    public void setConNombre(String conNombre) {
        this.conNombre = conNombre;
    }
    public String getConDireccion() {
        return this.conDireccion;
    }
    
    public void setConDireccion(String conDireccion) {
        this.conDireccion = conDireccion;
    }
    public String getConTelefonoFijo() {
        return this.conTelefonoFijo;
    }
    
    public void setConTelefonoFijo(String conTelefonoFijo) {
        this.conTelefonoFijo = conTelefonoFijo;
    }
    public String getConCelular() {
        return this.conCelular;
    }
    
    public void setConCelular(String conCelular) {
        this.conCelular = conCelular;
    }
    public Date getConFechaRegistro() {
        return this.conFechaRegistro;
    }
    
    public void setConFechaRegistro(Date conFechaRegistro) {
        this.conFechaRegistro = conFechaRegistro;
    }
    public Set getTallers() {
        return this.tallers;
    }
    
    public void setTallers(Set tallers) {
        this.tallers = tallers;
    }




}


