package utilHibernate;
// Generated 16/03/2019 12:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Garantia generated by hbm2java
 */
public class Garantia  implements java.io.Serializable {


     private Integer idgarantia;
     private Cliente cliente;
     private Vehiculo vehiculo;
     private Date garFechaRegistro;
     private Integer garLlamadaVerificacion;
     private Set detalleGarantias = new HashSet(0);

    public Garantia() {
    }

	
    public Garantia(Cliente cliente, Vehiculo vehiculo) {
        this.cliente = cliente;
        this.vehiculo = vehiculo;
    }
    public Garantia(Cliente cliente, Vehiculo vehiculo, Date garFechaRegistro, Integer garLlamadaVerificacion, Set detalleGarantias) {
       this.cliente = cliente;
       this.vehiculo = vehiculo;
       this.garFechaRegistro = garFechaRegistro;
       this.garLlamadaVerificacion = garLlamadaVerificacion;
       this.detalleGarantias = detalleGarantias;
    }
   
    public Integer getIdgarantia() {
        return this.idgarantia;
    }
    
    public void setIdgarantia(Integer idgarantia) {
        this.idgarantia = idgarantia;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Date getGarFechaRegistro() {
        return this.garFechaRegistro;
    }
    
    public void setGarFechaRegistro(Date garFechaRegistro) {
        this.garFechaRegistro = garFechaRegistro;
    }
    public Integer getGarLlamadaVerificacion() {
        return this.garLlamadaVerificacion;
    }
    
    public void setGarLlamadaVerificacion(Integer garLlamadaVerificacion) {
        this.garLlamadaVerificacion = garLlamadaVerificacion;
    }
    public Set getDetalleGarantias() {
        return this.detalleGarantias;
    }
    
    public void setDetalleGarantias(Set detalleGarantias) {
        this.detalleGarantias = detalleGarantias;
    }




}


