package utilHibernate;
// Generated 16/03/2019 12:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MarcaVehiculo generated by hbm2java
 */
public class MarcaVehiculo  implements java.io.Serializable {


     private Integer idmarcasCarro;
     private String marNombreMarca;
     private Date marFechaRegistro;
     private Set vehiculos = new HashSet(0);

    public MarcaVehiculo() {
    }

    public MarcaVehiculo(String marNombreMarca, Date marFechaRegistro, Set vehiculos) {
       this.marNombreMarca = marNombreMarca;
       this.marFechaRegistro = marFechaRegistro;
       this.vehiculos = vehiculos;
    }
   
    public Integer getIdmarcasCarro() {
        return this.idmarcasCarro;
    }
    
    public void setIdmarcasCarro(Integer idmarcasCarro) {
        this.idmarcasCarro = idmarcasCarro;
    }
    public String getMarNombreMarca() {
        return this.marNombreMarca;
    }
    
    public void setMarNombreMarca(String marNombreMarca) {
        this.marNombreMarca = marNombreMarca;
    }
    public Date getMarFechaRegistro() {
        return this.marFechaRegistro;
    }
    
    public void setMarFechaRegistro(Date marFechaRegistro) {
        this.marFechaRegistro = marFechaRegistro;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


