package utilHibernate;
// Generated 16/03/2019 12:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pqrs generated by hbm2java
 */
public class Pqrs  implements java.io.Serializable {


     private Integer idpqrs;
     private Cliente cliente;
     private Usuario usuario;
     private Integer pqrTipo;
     private Integer pqrTipoLlamada;
     private String pqrDescripcion;
     private Date pqrFecha;
     private Date pqrHora;
     private Date pqrFechaRegistro;

    public Pqrs() {
    }

	
    public Pqrs(Cliente cliente, Usuario usuario) {
        this.cliente = cliente;
        this.usuario = usuario;
    }
    public Pqrs(Cliente cliente, Usuario usuario, Integer pqrTipo, Integer pqrTipoLlamada, String pqrDescripcion, Date pqrFecha, Date pqrHora, Date pqrFechaRegistro) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.pqrTipo = pqrTipo;
       this.pqrTipoLlamada = pqrTipoLlamada;
       this.pqrDescripcion = pqrDescripcion;
       this.pqrFecha = pqrFecha;
       this.pqrHora = pqrHora;
       this.pqrFechaRegistro = pqrFechaRegistro;
    }
   
    public Integer getIdpqrs() {
        return this.idpqrs;
    }
    
    public void setIdpqrs(Integer idpqrs) {
        this.idpqrs = idpqrs;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getPqrTipo() {
        return this.pqrTipo;
    }
    
    public void setPqrTipo(Integer pqrTipo) {
        this.pqrTipo = pqrTipo;
    }
    public Integer getPqrTipoLlamada() {
        return this.pqrTipoLlamada;
    }
    
    public void setPqrTipoLlamada(Integer pqrTipoLlamada) {
        this.pqrTipoLlamada = pqrTipoLlamada;
    }
    public String getPqrDescripcion() {
        return this.pqrDescripcion;
    }
    
    public void setPqrDescripcion(String pqrDescripcion) {
        this.pqrDescripcion = pqrDescripcion;
    }
    public Date getPqrFecha() {
        return this.pqrFecha;
    }
    
    public void setPqrFecha(Date pqrFecha) {
        this.pqrFecha = pqrFecha;
    }
    public Date getPqrHora() {
        return this.pqrHora;
    }
    
    public void setPqrHora(Date pqrHora) {
        this.pqrHora = pqrHora;
    }
    public Date getPqrFechaRegistro() {
        return this.pqrFechaRegistro;
    }
    
    public void setPqrFechaRegistro(Date pqrFechaRegistro) {
        this.pqrFechaRegistro = pqrFechaRegistro;
    }




}


