package utilHibernate;
// Generated 16/03/2019 12:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Repuesto generated by hbm2java
 */
public class Repuesto  implements java.io.Serializable {


     private Integer idrepuesto;
     private String repSerial;
     private String repNombre;
     private Date repFechaRegistro;
     private Set detalleGarantias = new HashSet(0);

    public Repuesto() {
    }

    public Repuesto(String repSerial, String repNombre, Date repFechaRegistro, Set detalleGarantias) {
       this.repSerial = repSerial;
       this.repNombre = repNombre;
       this.repFechaRegistro = repFechaRegistro;
       this.detalleGarantias = detalleGarantias;
    }
   
    public Integer getIdrepuesto() {
        return this.idrepuesto;
    }
    
    public void setIdrepuesto(Integer idrepuesto) {
        this.idrepuesto = idrepuesto;
    }
    public String getRepSerial() {
        return this.repSerial;
    }
    
    public void setRepSerial(String repSerial) {
        this.repSerial = repSerial;
    }
    public String getRepNombre() {
        return this.repNombre;
    }
    
    public void setRepNombre(String repNombre) {
        this.repNombre = repNombre;
    }
    public Date getRepFechaRegistro() {
        return this.repFechaRegistro;
    }
    
    public void setRepFechaRegistro(Date repFechaRegistro) {
        this.repFechaRegistro = repFechaRegistro;
    }
    public Set getDetalleGarantias() {
        return this.detalleGarantias;
    }
    
    public void setDetalleGarantias(Set detalleGarantias) {
        this.detalleGarantias = detalleGarantias;
    }




}


