package utilHibernate;
// Generated 16/03/2019 12:45:30 PM by Hibernate Tools 4.3.1



/**
 * TipoCombustible generated by hbm2java
 */
public class TipoCombustible  implements java.io.Serializable {


     private Integer idtipoCombustible;
     private String comNombre;

    public TipoCombustible() {
    }

    public TipoCombustible(String comNombre) {
       this.comNombre = comNombre;
    }
   
    public Integer getIdtipoCombustible() {
        return this.idtipoCombustible;
    }
    
    public void setIdtipoCombustible(Integer idtipoCombustible) {
        this.idtipoCombustible = idtipoCombustible;
    }
    public String getComNombre() {
        return this.comNombre;
    }
    
    public void setComNombre(String comNombre) {
        this.comNombre = comNombre;
    }




}


