package utilHibernate;
// Generated 16/03/2019 12:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private Cargo cargo;
     private String usuNombre;
     private String usuApellido;
     private String usuNombreUsuario;
     private String usuContrasenia;
     private Integer usuEstado;
     private Date usuFechaRegistro;
     private Set pqrses = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Cargo cargo) {
        this.cargo = cargo;
    }
    public Usuario(Cargo cargo, String usuNombre, String usuApellido, String usuNombreUsuario, String usuContrasenia, Integer usuEstado, Date usuFechaRegistro, Set pqrses) {
       this.cargo = cargo;
       this.usuNombre = usuNombre;
       this.usuApellido = usuApellido;
       this.usuNombreUsuario = usuNombreUsuario;
       this.usuContrasenia = usuContrasenia;
       this.usuEstado = usuEstado;
       this.usuFechaRegistro = usuFechaRegistro;
       this.pqrses = pqrses;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getUsuApellido() {
        return this.usuApellido;
    }
    
    public void setUsuApellido(String usuApellido) {
        this.usuApellido = usuApellido;
    }
    public String getUsuNombreUsuario() {
        return this.usuNombreUsuario;
    }
    
    public void setUsuNombreUsuario(String usuNombreUsuario) {
        this.usuNombreUsuario = usuNombreUsuario;
    }
    public String getUsuContrasenia() {
        return this.usuContrasenia;
    }
    
    public void setUsuContrasenia(String usuContrasenia) {
        this.usuContrasenia = usuContrasenia;
    }
    public Integer getUsuEstado() {
        return this.usuEstado;
    }
    
    public void setUsuEstado(Integer usuEstado) {
        this.usuEstado = usuEstado;
    }
    public Date getUsuFechaRegistro() {
        return this.usuFechaRegistro;
    }
    
    public void setUsuFechaRegistro(Date usuFechaRegistro) {
        this.usuFechaRegistro = usuFechaRegistro;
    }
    public Set getPqrses() {
        return this.pqrses;
    }
    
    public void setPqrses(Set pqrses) {
        this.pqrses = pqrses;
    }




}


