package utilHibernate;
// Generated 16/03/2019 12:45:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String vin;
     private MarcaVehiculo marcaVehiculo;
     private TipoVehiculo tipoVehiculo;
     private String matricula;
     private Integer anioFabricacion;
     private Integer cilindraje;
     private Integer idTipoCombustible;
     private String modelo;
     private String color;
     private Integer numeroSillas;
     private Date fechaRegistro;
     private String paisFabricacion;
     private Integer costo;
     private Integer precioVenta;
     private String nombre;
     private Set garantias = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String vin, MarcaVehiculo marcaVehiculo, TipoVehiculo tipoVehiculo) {
        this.vin = vin;
        this.marcaVehiculo = marcaVehiculo;
        this.tipoVehiculo = tipoVehiculo;
    }
    public Vehiculo(String vin, MarcaVehiculo marcaVehiculo, TipoVehiculo tipoVehiculo, String matricula, Integer anioFabricacion, Integer cilindraje, Integer idTipoCombustible, String modelo, String color, Integer numeroSillas, Date fechaRegistro, String paisFabricacion, Integer costo, Integer precioVenta, String nombre, Set garantias) {
       this.vin = vin;
       this.marcaVehiculo = marcaVehiculo;
       this.tipoVehiculo = tipoVehiculo;
       this.matricula = matricula;
       this.anioFabricacion = anioFabricacion;
       this.cilindraje = cilindraje;
       this.idTipoCombustible = idTipoCombustible;
       this.modelo = modelo;
       this.color = color;
       this.numeroSillas = numeroSillas;
       this.fechaRegistro = fechaRegistro;
       this.paisFabricacion = paisFabricacion;
       this.costo = costo;
       this.precioVenta = precioVenta;
       this.nombre = nombre;
       this.garantias = garantias;
    }
   
    public String getVin() {
        return this.vin;
    }
    
    public void setVin(String vin) {
        this.vin = vin;
    }
    public MarcaVehiculo getMarcaVehiculo() {
        return this.marcaVehiculo;
    }
    
    public void setMarcaVehiculo(MarcaVehiculo marcaVehiculo) {
        this.marcaVehiculo = marcaVehiculo;
    }
    public TipoVehiculo getTipoVehiculo() {
        return this.tipoVehiculo;
    }
    
    public void setTipoVehiculo(TipoVehiculo tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Integer getAnioFabricacion() {
        return this.anioFabricacion;
    }
    
    public void setAnioFabricacion(Integer anioFabricacion) {
        this.anioFabricacion = anioFabricacion;
    }
    public Integer getCilindraje() {
        return this.cilindraje;
    }
    
    public void setCilindraje(Integer cilindraje) {
        this.cilindraje = cilindraje;
    }
    public Integer getIdTipoCombustible() {
        return this.idTipoCombustible;
    }
    
    public void setIdTipoCombustible(Integer idTipoCombustible) {
        this.idTipoCombustible = idTipoCombustible;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Integer getNumeroSillas() {
        return this.numeroSillas;
    }
    
    public void setNumeroSillas(Integer numeroSillas) {
        this.numeroSillas = numeroSillas;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getPaisFabricacion() {
        return this.paisFabricacion;
    }
    
    public void setPaisFabricacion(String paisFabricacion) {
        this.paisFabricacion = paisFabricacion;
    }
    public Integer getCosto() {
        return this.costo;
    }
    
    public void setCosto(Integer costo) {
        this.costo = costo;
    }
    public Integer getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(Integer precioVenta) {
        this.precioVenta = precioVenta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getGarantias() {
        return this.garantias;
    }
    
    public void setGarantias(Set garantias) {
        this.garantias = garantias;
    }




}


